### PR TITLE
patch fix windows build (second time)

### PR DESCRIPTION
**Pull request by leanid**
fixed all review comments: https://github.com/jrosdahl/ccache/pull/39
please check it.

### CODE REVIEW

**Comment by jrosdahl** [comment]
Will `-lws2_32` work for 64-bit builds  as well?

**Comment by TheOneRing** [comment]
Yes.

**Comment by jrosdahl** [comment]
OK, then something like this should work (untested):

    diff --git a/configure.ac b/configure.ac
    index 2cf2939..9e65588 100644
    --- a/configure.ac
    +++ b/configure.ac
    @@ -11,6 +11,7 @@ AC_CANONICAL_HOST
     
     case $host in
         *mingw32* | *cygwin* | *wince* | *mingwce*)
    +        windows_os=yes
             AC_DEFINE(_WIN32_WINNT,0x0600, Windows Vista or newer is required)
             ;;
     esac
    @@ -122,6 +123,11 @@ else
         extra_ldflags="-lz"
     fi
     
    +dnl Linking on Windows needs ws2_32
    +if test x${windows_os} = xyes; then
    +    extra_ldflags="$extra_ldflags -lws2_32"
    +fi
    +
     AC_C_BIGENDIAN
     
     AC_C_INLINE

Can you try if it works?

**Comment by TheOneRing** [comment]
works perfectly. 

Ship it ! :)

**Comment by TheOneRing** [comment]
ship it?

**Comment by jrosdahl** [comment]
There are still issues left, but I decided to attempt to address them "blindly". Since I can't check if I have made some mistakes, please try it out (latest 3.2-maint or master).

**Comment by TheOneRing** [comment]
Hi master compiles and seems to work, haven't seen a crash or something like that.
Anything special I should check for?

**Comment by jrosdahl** [comment]
Don't think so, if it compiles I'm quite confident with the changes. :-)

Thanks for testing, and thanks leanid for the patches!

**Pull request closed without merging**
